# links are currently irrelevant. Once docker-compose supports --add-host, the links should be replaced.
pythonbase:
  build: pythonbase
javabase:
  build: javabase
elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
  volumes_from:
    - elasticsearchdata
  volumes:
    - /var/log/cloudify/elasticsearch:/etc/service/elasticsearch/logs
elasticsearchdata:
  image: docker_elasticsearch
  command: echo Elasticsearch Data Container
logstash:
  build: logstash
  ports:
    - "9999:9999"
  links:
    - elasticsearch
    - rabbitmq
  volumes:
    - /var/log/cloudify/logstash:/etc/service/logstash/logs
kibana:
  build: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
rabbitmq:
  build: rabbitmq
  ports:
    - "5672:5672"
influxdb:
  build: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8099:8099"
  volumes_from:
    - influxdbdata
influxdbdata:
  image: docker_influxdb
  command: echo InfluxDB Data Container
amqpinflux:
  build: amqpinflux
  links:
    - rabbitmq
    - influxdb
riemann:
  build: riemann
  links:
    - rabbitmq
    - frontend
  volumes_from:
    - riemanndata
  volumes:
    - /var/log/cloudify/riemann:/etc/service/riemann/logs
riemanndata:
  image: docker_riemann
  command: echo Riemann Data Container
mgmtworker:
  build: mgmtworker
  links:
    - rabbitmq
    - frontend
frontend:
  build: frontend
  links:
    - elasticsearch
    - rabbitmq
  ports:
    - "80:80"
    - "53229:53229"
    - "8100:8100"
    - "9001:9001"
  volumes_from:
    - frontenddata
frontenddata:
  image: docker_frontend
  command: echo Frontend Data Container
webui:
  build: webui
restservice:
  build: restservice
logio:
  build: logio
targethost:
  build: targethost
fileserver:
  build: fileserver