javabase:
  build: javabase
# nginx:
#   build: nginx
#   ports:
#     - "80:80"
#     - "53229:53229"
#   links:
#     - webui
#     - restservice
#   volumes_from:
#     - webui
    # - fileserverdata
# fileserverdata:
#   image: docker_nginx
#   command: echo FileServer Data Container
elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
  volumes_from:
    - elasticsearchdata
  volumes:
    - /var/log/cloudify/elasticsearch:/etc/service/elasticsearch/logs
elasticsearchdata:
  image: docker_elasticsearch
  command: echo Elasticsearch Data Container
logstash:
  build: logstash
  ports:
    - "9999:9999"
  links:
    - elasticsearch
    - rabbitmq
  volumes:
    - /var/log/cloudify/logstash:/etc/service/logstash/logs
kibana:
  build: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
rabbitmq:
  build: rabbitmq
  ports:
    - "5672:5672"
influxdb:
  build: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8099:8099"
#   volumes_from:
#     - influxdbdata
# influxdbdata:
#   image: docker_influxdb
#   command: echo InfluxDB Data Container
riemann:
  build: riemann
  links:
    - rabbitmq
    # - restservice
  volumes_from:
    - riemanndata
  volumes:
    - /var/log/cloudify/riemann:/etc/service/riemann/logs
riemanndata:
  image: docker_riemann
  command: echo Riemann Data Container
# restservice:
#   build: restservice
#   ports:
#     - "8100:8100"
#   links:
#     - elasticsearch
#     - rabbitmq
#   volumes_from:
#     - restservicedata
# restservicedata:
#   image: docker_restservice
#   command: echo Rest Service Data Container
# mgmtworker:
#   build: mgmtworker
#   links:
#     - rabbitmq
#     - restservice
# webui:
#   build: webui
#   ports:
#     - "9001:9001"

# restart_policy: always
# ~/:/tmp/home
# /root
# /var/log/cloudify