nginx:
  build: nginx
  ports:
    - "80:80"
elasticsearch:
  build: elasticsearch
  ports:
    - "9200:9200"
logstash:
  build: logstash
  ports:
    - "9999:9999"
  links:
    - elasticsearch
    - rabbitmq
rabbitmq:
  build: rabbitmq
  ports:
    - "5672:5672"
influxdb:
  build: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8099:8099"
# riemann:
#   build: riemann
#   links:
#     - rabbitmq