nginx:
  image: cloudify/nginx
  command: /sbin/my_init
  ports:
    - "80:80"
elasticsearch:
  image: cloudify/elasticsearch
  command: /sbin/my_init
  ports:
    - "9200:9200"
# logstash:
#   image: cloudify/logstash
#   command: /sbin/my_init
#   ports:
#     - "9999:9999"
#   links:
#     - elasticsearch
#     - rabbitmq
rabbitmq:
  image: cloudify/rabbitmq
  command: /sbin/my_init
  ports:
    - "5672:5672"
influxdb:
  image: cloudify/influxdb
  command: /sbin/my_init
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8099:8099"
# riemann:
#   image: cloudify/riemann
#   command: /sbin/my_init
#   links:
#     - rabbitmq
